<a href="https://colab.research.google.com/github/MayaPikachu/Offense-detector/blob/main/Offense_Detector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers
!pip install unidecode
!pip install tokenizers

!gdown --fuzzy "https://drive.google.com/uc?id=18VOWo-rHUiQ7pIlzzMzkFCrZNX0RIWCe"
!gdown --fuzzy "https://drive.google.com/uc?id=1G-bAySkxcI1laV9wDkWGF1mxENICzglN"

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from transformers import AutoTokenizer
from unidecode import unidecode
from tokenizers import ByteLevelBPETokenizer

df = pd.read_csv("SBIC.v2.trn.csv")
dt = pd.read_csv("SBIC.v2.tst.csv")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 5.1 MB/s eta 0:00:00
Downloading...
From: https://drive.google.com/uc?id=18VOWo-rHUiQ7pIlzzMzkFCrZNX0RIWCe
To: /content/SBIC.v2.trn.csv
100% 27.7M/27.7M [00:00<00:00, 70.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1G-bAySkxcI1laV9wDkWGF1mxENICzglN
To: /content/SBIC.v2.tst.csv
100% 4.40M/4.40M [00:00<00:00, 105MB/s]


In [ ]:
vocab_size = 10000

poststrn = df.post.values
resultstrn = df.offensiveYN.values

poststst = dt.post.values
resultstst = dt.offensiveYN.values

tokenizer = ByteLevelBPETokenizer()
tokenizer.train_from_iterator([poststrn[:int(4E7)]], vocab_size, min_frequency=5)

vocab_size = tokenizer.get_vocab_size()

print(f"\n\n\tTokenizado! Vocab_size = {vocab_size}\n")

encode = lambda s: tokenizer.encode(s).ids
decode = lambda ids: tokenizer.decode(ids)

print(np.unique(resultstrn, return_counts = True))



	Tokenizado! Vocab_size = 10000

(array([0. , 0.5, 1. , nan]), array([46673,  9992, 54218,  2017]))


In [ ]:
#Hyperparameters
batch_size = 64 #B
block_size = 42 #T
n_embd = 128 #C -> A embedding table recebe um input de dimensão B, T, ou seja, batch_size exemplos de block_size tamanho cada. Cada exemplo colocado puxa uma linha de tamanho n_embd de logits, por isso B, T, C, sendo C os logits lidos
iter = 25000
learning_rate = 1e-4
dropout = 0.20
n_head = 4
n_layer = 2
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def get_data(file, results, batch_size=batch_size):
    X, Y = [], []
    for _ in range(batch_size):
        ix = torch.randint(0, len(file), (1,))
        input = (encode(file[ix]) + [0] * block_size)[:block_size]
        X.append(input)
        Y.append(results[ix].item())  # Ensure Y is a single scalar per sequence
    return torch.tensor(X).float(), torch.nan_to_num(torch.tensor(Y).float(), nan = 0)

A, B = get_data(poststrn, resultstrn)
A.shape

torch.Size([64, 42])

In [ ]:

class Head(nn.Module):
  def __init__(self, head_size):
    super().__init__()
    #as linear layers vão aprendendo, já que recebem o vetor de características de tokens específicos, então conseguem deduzir informações sobre esses tokens com o passar do tempo
    self.key = nn.Linear(n_embd, head_size, bias=False)
    self.query = nn.Linear(n_embd, head_size, bias=False)
    self.value = nn.Linear(n_embd, head_size, bias=False)
    self.dropout = nn.Dropout(dropout)

  def forward(self, x):
    B, T, C = x.shape
    k = self.key(x)
    q = self.query(x)
    v = self.value(x)
    wei = q @ k.transpose(-2, -1) * C**-0.5
    wei = F.softmax(wei, dim=-1)
    wei = self.dropout(wei)
    out = wei @ v
    return out

class MultiHeadAttention(nn.Module):
  def __init__(self, num_heads, head_size):
    super().__init__()
    #Divide o processamento em várias heads, que vão obter informações diferentes para cada token/frase, e então concatena
    self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
    self.proj = nn.Linear(n_embd, n_embd)
    self.dropout = nn.Dropout(dropout)

  def forward(self, x):
    out = torch.cat([h(x) for h in self.heads], dim=-1)
    out = self.dropout(self.proj(out))
    return out

class MLP(nn.Module):
  def __init__(self):
    super().__init__()
    self.l1 = nn.Linear(n_embd, 4*n_embd)
    self.l2 = nn.Linear(4*n_embd, n_embd)

  def forward(self, x):
    x = F.relu(self.l1(x))
    x = nn.Dropout(0.2)(self.l2(x))

    return x

class Block(nn.Module):
  def __init__(self, n_embd, n_head):
    super().__init__()
    #MultiHeadAttention faz a comunicação entre os tokens, e a MLP faz a computação dos graus de ofensividade
    head_size = n_embd // n_head
    self.sa = MultiHeadAttention(n_head, head_size)
    self.ffwd = MLP()
    self.ln1 = nn.LayerNorm(n_embd)
    self.ln2 = nn.LayerNorm(n_embd)

  def forward(self, x):
    x = x + self.sa(self.ln1(x))
    x = x + self.ffwd(self.ln2(x))
    return x


class BigramLanguageModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(
            *[Block(n_embd, n_head=n_head) for _ in range(n_layer)]
        )
        self.ln_f = nn.LayerNorm(n_embd)
        #lm_head transforma os resultados do formato B, T, C (C é o mesmo que n_embd) em B, T, 1
        #Assim, o formato representa B (batch_size) frases de T (Time dimension = block_size) tokens, cada token representado por um único número
        #Esse número depois será passado para um conjunto de funções que tem como objetivo definir um grau único de ofensividade para a frase
        self.lm_head = nn.Linear(n_embd, 1)


    def forward(self, idx, targets=None):
        B, T = idx.shape


        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb

        x = self.blocks(x)

        x = self.ln_f(x)

        #logits é o grau de ofensividade de cada token
        #tlogits é o da frase como um todo
        logits = self.lm_head(x).squeeze(-1).float()
        Sigmoide e média não parecem ser funções muito adequadas, testar outras funções, e talvez alguma forma de softmax
        logits = nn.Sigmoid()(logits)
        tlogits = logits.mean(dim = 1).float()
        print(logits[30])

        if targets is  None:
            loss = None
            return logits, loss

        else:
            # Qualidade
            tlogits = logits.mean(dim = 1).float()
            print(logits[30])
            tlogits  = tlogits.view(B)

            targets = targets.float()

            loss = nn.BCEWithLogitsLoss()(tlogits, targets)

        return tlogits, loss

model = BigramLanguageModel()
model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for i in range(iter):
    X, Y = get_data(poststrn, resultstrn)
    X = X.to(device).long()
    Y = Y.to(device)

    optimizer.zero_grad()
    logits, loss = model(X, Y)
    loss.backward()
    optimizer.step()

    #if i % 10 == 0:
       # print(f'step = {i}, loss = {loss.item()}')

Streaming output truncated to the last 5000 lines.
tensor([0.9997, 0.9997, 0.9998, 0.9998, 0.9998, 0.9998, 0.9998, 0.9998, 0.9996,
        0.9998, 0.9999, 0.9998, 0.9997, 0.9999, 0.9999, 0.9999, 0.9981, 0.9999,
        0.9993, 0.9994, 0.9996, 0.9997, 0.9997, 0.9999, 0.9986, 0.9992, 0.9999,
        0.9998, 0.9999, 0.9999, 0.9998, 0.9997, 0.9999, 0.9999, 0.9998, 0.9999,
        0.9999, 0.9991, 0.9996, 0.9998, 0.9999, 0.9999], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 0.9999, 1.0000, 0.9999, 0.9999, 1.0000, 1.0000, 1.0000,
        0.9999, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 0.9999, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([3.5579e-05, 3.5083e-05, 3.6545e-05, 3.1152e-05, 3.5849e-05, 2.6343e-05,
        3.049

KeyboardInterrupt: 

In [ ]:
precisao = 0.0
for i in range(100):
  X, Y = get_data(poststst, resultstst)
  X = X.to(device).long()

  logits = model(X)[0]
  precisao += (np.around(list(logits.cpu().detach().numpy()), 1) == Y.unsqueeze(1)).float().mean()/100.
  print(f'x: {decode(X[1].int().to("cpu").tolist())}, y = {Y[1].to("cpu")}, predito = {0 if logits[1].to("cpu").item() < .33 else 0.5 if logits[1].to("cpu").item() < 0.66 else 1}')
  print(precisao)



In [ ]:
X, Y = get_data(poststrn, resultstrn)
X = X.long()
print(X.shape)
C = nn.Embedding(vocab_size, n_embd)(X)
print(torch.max(C, dim=-1))
print(C.shape)
print(vocab_size)

#parte retirada para testes
nn.Sequential(
            nn.Linear(n_embd, 4*n_embd),
            nn.LayerNorm(4*n_embd),
            nn.ReLU(),
            nn.Linear(4*n_embd, n_embd),
            nn.LayerNorm(n_embd),
            nn.ReLU(),
            nn.Linear(n_embd, 1),
            )

torch.Size([64, 42])
torch.return_types.max(
values=tensor([[2.3487, 2.4277, 2.2341,  ..., 2.5106, 2.5106, 2.5106],
        [2.5543, 2.9038, 2.3633,  ..., 2.5106, 2.5106, 2.5106],
        [2.1183, 3.0191, 2.2370,  ..., 2.5106, 2.5106, 2.5106],
        ...,
        [2.8487, 3.1020, 2.7489,  ..., 2.5106, 2.5106, 2.5106],
        [2.8487, 2.5223, 2.2177,  ..., 2.5106, 2.5106, 2.5106],
        [2.8487, 2.5223, 2.2341,  ..., 2.5106, 2.5106, 2.5106]],
       grad_fn=<MaxBackward0>),
indices=tensor([[ 51, 123, 125,  ...,  49,  49,  49],
        [107,  16,  59,  ...,  49,  49,  49],
        [ 42,  70, 123,  ...,  49,  49,  49],
        ...,
        [ 25, 100,  54,  ...,  49,  49,  49],
        [ 25,  72,  38,  ...,  49,  49,  49],
        [ 25,  72, 125,  ...,  49,  49,  49]]))
torch.Size([64, 42, 128])
10000
